
FROM oven/bun

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY .npmrc package.json turbo.json bun.lock ./
COPY packages/db/package.json ./packages/db/package.json
COPY packages/nodes-base/package.json ./packages/nodes-base/package.json
COPY packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY packages/typescript-config/package.json ./packages/typescript-config/package.json
COPY packages/ui/package.json ./packages/ui/package.json
COPY apps/web/package.json ./apps/web/package.json

RUN bun install

COPY packages ./packages
COPY apps/web ./apps/web

WORKDIR /usr/src/app/packages/db
RUN bunx prisma generate

WORKDIR /usr/src/app/apps/web

RUN --mount=type=secret,id=envfile \
    export $(cat /run/secrets/envfile | xargs) && \
    bun run build

EXPOSE 4000

CMD ["bun", "start"]